import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { NavBar } from '@/components/ui/NavBar';
import { cn } from '@/lib/utils/cn';
import { UserContextProvider } from '@/contexts/user/Provider';
import { fetchMe } from '@/contexts/user/fetch'

import './globals.css';

const intInter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: [
    {
      url: '/logo.svg',
      rel: 'icon',
      type: 'image/svg+xml',
    },
  ],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialUser = await fetchMe();

  return (
    <html lang='en'>
      <body className={cn('font-sans relative', intInter.className)}>
        <div className='flex flex-col min-h-screen'>
          <UserContextProvider initialUser={initialUser}>
            <NavBar className='w-full' />

            <main>{children}</main>
          </UserContextProvider>
        </div>
      </body>
    </html>
  );
}
